[versions]
jjwt = "0.12.6"
springdoc = "2.7.0"
bucket4j = "8.10.1"
caffeine = "3.1.8"
minio = "8.5.14"
aws-s3 = "2.29.46"
jooq = "3.19.16"
mockk = "1.13.13"
resilience4j = "2.2.0"

[libraries]
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
springdoc-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
bucket4j = { module = "com.bucket4j:bucket4j-core", version.ref = "bucket4j" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
minio = { module = "io.minio:minio", version.ref = "minio" }
aws-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws-s3" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
resilience4j-spring = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j" }
resilience4j-retry = { module = "io.github.resilience4j:resilience4j-retry", version.ref = "resilience4j" }
